@plr = player()



@hero = associative_array(
            'name': '§eI§fro§en §fFi§es§ft',
            'class': 'lukecage',
            'sig': '0130299a4489429db4eb68643a4c6ac8,
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzczNTA1NTg4NzgsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2RmYTI5OTY4MWEwNjZmZGU1YTUxOGU3YTIyNTkxY2YwOTdlZGI1ODk5NmQwY2M4YzgwMzVkYWY3OTU4NCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Its time to get rocky!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-5",
                "/haste 0-9",
                
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 15 true"                
            )
        )
